name: Publish plugin on release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run tests
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: |
            --stacktrace
            check -x :artifact-tests:test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          check_name: JUnit Test Report
          report_paths: '**/build/test-results/**/TEST-*.xml'
          annotate_notice: false

  artifact_tests:
    runs-on: ubuntu-latest
    env:
      ENABLE_JAR_CACHING: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run artifact tests
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: |
            --stacktrace
            :artifact-tests:check
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          check_name: JUnit Artifact Test Report
          report_paths: '**/build/test-results/**/TEST-*.xml'
          annotate_notice: false

  release:
    needs:
      - build
      - artifact_tests
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Publish plugin
        uses: gradle/actions/setup-gradle@v3
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.OSSRH_GPG_SECRET_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_withSigning: true
        with:
          arguments: |
            -Pversion=${{ github.event.release.tag_name }}
            -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
            -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
            --stacktrace
            assemble publishPlugins publishToSonatype closeAndReleaseSonatypeStagingRepository
      - name: Attach artifacts to the release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'build/libs/jooq-gradle-plugin-*[0-9].*[0-9].*[0-9]{-javadoc,-sources,}.jar'
          file_glob: true
          tag: ${{ github.ref }}
